travis:
  secure:
    BINSTAR_TOKEN: njqiSzmx5//mP6ZtBmXt47CsjhOgfPrhghmR4HYIS9bURlgHj2fN2fZYVj9Fx0zT7CQmxEl58g6CL1kM/q0D07IBOYdb3rkL+kUBACSckXTM6hnaExoi9aqQxvAdcCCKh93Nla1dXeea9vU1C5ulMd4t6wePFq/SDAQHP6pqfalzSx9caqK6Gk08zcB2U5y6aDV0qmpmHDeMrw1n/MBYmEJZBo/3CpWns3RVlr9hwZOqgLfzcf0RlY+qoa3K+jXVmyBRY9cRhzR5xTeyx2GgITpioxezUBF3iW5o2cWrhZaLG+Xya3sbLR5A4zsdHyzKVMI0J940WpX/b/TUsucV/0ZCvLuwyDwmwOey8r2U5e3EbBnm9YCkp2jolNvwAQ7NY+5v10+l7ZGPa15nWgTSa4MNqeeMLTHk+x7yciVaIoopexgguVLBfOZt6i422QA78wBUPMQlIkJ2rm0aOE51531rKQ4761cb9Pv9kk2TV5oySqRYl63QSr6biXb7xkVbbuQxSh26afulAmVEoWQjr93ySSOA9/aFMCBIVfMLPS1nATQrinLJVHxPsa5sH6sFHbyY1enNvMHMSGXRql7KOkTU6mXSk+ZAcP/A7Bm5Xz9fjBVKNx+IQmYBJPY79y+KeaNjfCkm4FJLr3ZB1eomA+95bzTFfbCpgpHCrtUH5xI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
